### ISSUE TITLE
FR: MediaInfo on hover:action

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#114]
I keep several versions of the really good movies and TV shows just for this reason.... streaming. If I am using a capped ISP to stream I want to watch my xvid 700mb version.. if uncapped I want my 720/1080p 4-8GB versions. 

It would be helpful to display mediainfo in a hover balloon for each video.

**Comment by oxan** [comment]
I think we should handle multiple versions of some movies and TV shows better anyway... I think for TV shows I already worked around this (just because I use it :P), but mopi probably has some bugs.

**Comment by tlindener** [comment]
First of all hover and anything like it is nice, but since mobile devices like tablets don't have this ability i will try to reduce the amount of ui features which don't work cross platform. Never the less it should be able to "see" which movie has which quality and based on my latest design ideas i'm quite sure this information will be visible.

**Comment by oxan** [comment]
See mediainfo branch. We need to cache this stuff.

**Comment by oxan** [comment]
Implemented with 33d810.

**Comment by lyfesaver** [comment]
thx!!!
